sudo: required
dist: trusty

language:
  - cpp

matrix:
  include:
    - env: BUILD=DEBUG
      compiler: gcc

    - env: BUILD=RELEASE
      compiler: gcc

    - env: BUILD=DEBUG
      compiler: clang

    - env: BUILD=RELEASE
      compiler: clang

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install -qq clang libc++-dev libc++abi-dev; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++"; fi
  - wget https://cmake.org/files/v3.7/cmake-3.7.1.tar.gz
  - tar xf cmake-3.7.1.tar.gz
  - cd cmake-3.7.1
  - ./configure
  - make
  - sudo make install
  - cd ..
  - PROJECT_DIR=`pwd`
  - BOOST=$HOME/boost
  - git clone --depth 1 -b boost-1.62.0 https://github.com/boostorg/boost.git $BOOST
  - cd $BOOST
  - git submodule update --init --merge
  - ./bootstrap.sh
  - ./b2 headers
  - cd $PROJECT_DIR

script:
  - $CXX --version
  - cmake --version
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD} -DBOOST_ROOT="$BOOST"
  - make
  - ./test/nemo_tests
  - ./bench/nemo_benchmark

